### ISSUE TITLE
build_visit fails on mpich 3.0.4 on Mac 10.8.5

### ISSUE THREAD

**Issue by aowen87** [aowen87/BAR#1887]
I was rebuilding my 3rd party libraries to pick up new versions of libraries(like VTK). Apparently MPICH was updated to 3.0.4 and this fails to build on my 10.8.5 Mac. MPICH 3.0.1 was the last one I built using build_visit and that worked. Maybe MPICH 3.1 needs to be used instead?

Here's where the build fails:
 Making all in .
  CC       bsci_init.lo
  CCLD     libhydra.la
  CCLD     hydra_persist
  CCLD     hydra_nameserver
  CCLD     hydra_pmi_proxy
  CCLD     mpiexec.hydra
 duplicate symbol _HYD_pmcd_pmip in:
    hydra_pmi_proxy-pmip.o
    hydra_pmi_proxy-pmip_cb.o
 duplicate symbol _HYD_pmcd_pmip in:
    hydra_pmi_proxy-pmip.o
    hydra_pmi_proxy-pmip_utils.o
 ld: 2 duplicate symbols for architecture x86_64
 collect2: ld returned 1 exit status
 make[3]: *** [hydra_pmi_proxy] Error 1
 make[3]: *** Waiting for unfinished jobs....
 make[2]: *** [all-recursive] Error 1
 make[1]: *** [all-recursive] Error 1
 make: *** [all] Error 2

-----------------------REDMINE MIGRATION-----------------------
This ticket was migrated from Redmine. As such, not all 
information was able to be captured in the transition. Below is
a complete record of the original redmine ticket.

Ticket number: 1754
Status: Resolved
Project: VisIt
Tracker: Bug
Priority: Normal
Subject: build_visit fails on mpich 3.0.4 on Mac 10.8.5
Assigned to: Cyrus Harrison
Category: 
Target version: 2.7.2
Author: Brad Whitlock
Start: 02/26/2014
Due date: 
% Done: 0
Estimated time: 
Created: 02/26/2014 07:51 pm
Updated: 03/17/2014 06:48 pm
Likelihood: 2 - Rare
Severity: 3 - Major Irritation
Found in version: 2.7.1
Impact: 
Expected Use: 
OS: OSX
Support Group: Any
Description:
 I was rebuilding my 3rd party libraries to pick up new versions of libraries(like VTK). Apparently MPICH was updated to 3.0.4 and this fails to build on my 10.8.5 Mac. MPICH 3.0.1 was the last one I built using build_visit and that worked. Maybe MPICH 3.1 needs to be used instead?

Here's where the build fails:
 Making all in .
  CC       bsci_init.lo
  CCLD     libhydra.la
  CCLD     hydra_persist
  CCLD     hydra_nameserver
  CCLD     hydra_pmi_proxy
  CCLD     mpiexec.hydra
 duplicate symbol _HYD_pmcd_pmip in:
    hydra_pmi_proxy-pmip.o
    hydra_pmi_proxy-pmip_cb.o
 duplicate symbol _HYD_pmcd_pmip in:
    hydra_pmi_proxy-pmip.o
    hydra_pmi_proxy-pmip_utils.o
 ld: 2 duplicate symbols for architecture x86_64
 collect2: ld returned 1 exit status
 make[3]: *** [hydra_pmi_proxy] Error 1
 make[3]: *** Waiting for unfinished jobs....
 make[2]: *** [all-recursive] Error 1
 make[1]: *** [all-recursive] Error 1
 make: *** [all] Error 2

Comments:
MPICH 3.1 fails too.
the problem is with the use of -fno-common,  3.0.4 may work, but we I need to trace down where fno-common is being introduced in build_visit
The -fno-common is being added to the CFLAGS and CXXFLAGS in bv_main.sh.
Hi Everyone,1) build_visit: avoid using -fno-common when building mpich2) release notes updates for 2.7.2.RC:Sending        bv_support/bv_mpich.shTransmitting file data .Committed revision r23023.Sending        en_US/relnotes2.7.2.htmlTransmitting file data .Committed revision r23024.Trunk:Sending        resources/help/en_US/relnotes2.7.2.htmlSending        svn_bin/bv_support/bv_mpich.shTransmitting file data ..Committed revision r23026.-Cyrus
