### ISSUE TITLE
build_visit fails on mpich 3.0.4 on Mac 10.8.5

### ISSUE THREAD

**Issue by aowen87** [aowen87/BAR#1889]
I was rebuilding my 3rd party libraries to pick up new versions of libraries(like VTK). Apparently MPICH was updated to 3.0.4 and this fails to build on my 10.8.5 Mac. MPICH 3.0.1 was the last one I built using build_visit and that worked. Maybe MPICH 3.1 needs to be used instead?

Here's where the build fails:
 Making all in .
  CC       bsci_init.lo
  CCLD     libhydra.la
  CCLD     hydra_persist
  CCLD     hydra_nameserver
  CCLD     hydra_pmi_proxy
  CCLD     mpiexec.hydra
 duplicate symbol _HYD_pmcd_pmip in:
    hydra_pmi_proxy-pmip.o
    hydra_pmi_proxy-pmip_cb.o
 duplicate symbol _HYD_pmcd_pmip in:
    hydra_pmi_proxy-pmip.o
    hydra_pmi_proxy-pmip_utils.o
 ld: 2 duplicate symbols for architecture x86_64
 collect2: ld returned 1 exit status
 make[3]: *** [hydra_pmi_proxy] Error 1
 make[3]: *** Waiting for unfinished jobs....
 make[2]: *** [all-recursive] Error 1
 make[1]: *** [all-recursive] Error 1
 make: *** [all] Error 2

-----------------------REDMINE MIGRATION-----------------------
This ticket was migrated from Redmine. The following information
could not be accurately captured in the new ticket:

Original author: Brad Whitlock
Original creation: 02/26/2014 07:51 pm
Original update: 03/17/2014 06:48 pm
Ticket number: 1754
